feat: cleaner 'all' menu with extmarks and nice mode lists
tris203/hawtkeys.nvim pull request #25
Opened 2023-12-19 00:09 UTC by willothy

![image](https://github.com/tris203/hawtkeys.nvim/assets/38540736/b2b5cb49-d3f3-4aa2-bff7-67301386029d)

2023-12-19 11:05 UTC, tris203 requested changes

2023-12-19 11:05 UTC, tris203 commented on lua/hawtkeys/ui.lua
> +            virt_lines = { { { l2, "Comment" } } },
I dont think I like the "action" being in comment highlighting, could we make this function highlighting and then make the filename in comment highlighting?

2023-12-20 09:23 UTC, tris203 commented
This looks great @willothy !

Thank you, do you think there is any reason that we cant use this as a general theme accross the whole plugin?

2023-12-20 09:26 UTC, tris203 approved these changes

2023-12-20 09:27 UTC, willothy commented
> This looks great @willothy !
> 
> Thank you, do you think there is any reason that we cant use this as a general theme accross the whole plugin?

Thanks! I can do some work with extmarks and highlighting for the rest of the UI, and try to unify things a bit. For example, I'd like to use overlay extmarks for the search character highlights instead of `[char]`

2023-12-20 09:27 UTC, tris203 commented
> > This looks great @willothy !
> > Thank you, do you think there is any reason that we cant use this as a general theme accross the whole plugin?
> 
> Thanks! I can do some work with extmarks and highlighting for the rest of the UI, and try to unify things a bit. For example, I'd like to use overlay extmarks for the search character highlights instead of `[char]`

would you like to do that in this PR or a seperate one?

2023-12-20 09:30 UTC, willothy commented
Probably a separate one, since this code likely won't be changed in it

2023-12-20 09:45 UTC, merged