feat: experimental mapping
tris203/hawtkeys.nvim pull request #26
Opened 2023-12-19 21:07 UTC by tris203

this refactors the mapping to take a config for custom maps

currently, it hits 4 of the example mapping functions

TODO: Hit the other mapping examples, if anyone has anymore please put them here or in the issue

Additionally, will need to keep the sensible defaults for the mapping definitions and offer a way to put them in through config and merge them with the defaults

2023-12-19 23:22 UTC, willothy approved these changes
lgtm once the queries are updated to use format strings

2023-12-20 00:11 UTC, tris203 commented
TODO:

 - Ability to set in config and merge in
 - Sensible defaults
 - Handle which key mappings - parse and hand off to ```which-key``` in a ```pcall```?
 - Handle lazy key maps ```(expression_list)```

2023-12-20 00:51 UTC, willothy commented on lua/hawtkeys/ts.lua
>      end
```suggestion
```

2023-12-20 00:52 UTC, willothy commented on lua/hawtkeys/ts.lua
>      end
oops accident

2023-12-20 00:55 UTC, willothy requested changes
should reuse the buildArgs function imo

2023-12-20 00:55 UTC, willothy commented on lua/hawtkeys/ts.lua
>      end
```suggestion
```

2023-12-20 00:55 UTC, willothy commented on lua/hawtkeys/ts.lua
>  ---@param mapDefs keyMapArgs[]
```suggestion
---@param params keyMapArgs[]
---@return string
local function buildArgs(params, method)
    local args = ""
    for name, opts in pairs(params) do
        if opts.method == method then
            args = args .. ' "' .. name .. '"'
        end
    end
    return args
end

---@param mapDefs keyMapArgs[]
```

2023-12-20 00:55 UTC, willothy commented on lua/hawtkeys/ts.lua
>      end
```suggestion
```

2023-12-20 00:55 UTC, willothy commented on lua/hawtkeys/ts.lua
> +    return string.format(query, buildArgs(mapDefs))
```suggestion
    return string.format(query, buildArgs(mapDefs, "function_call"))
```

2023-12-20 00:55 UTC, willothy commented on lua/hawtkeys/ts.lua
> +    return string.format(query, buildArgs(mapDefs))
```suggestion
    return string.format(query, buildArgs(mapDefs, "dot_index_expression"))
```
This way we avoid creating closures for each call, and reuse the buildArgs function

2023-12-20 11:35 UTC, willothy commented on lua/hawtkeys/ts.lua
> +local function buildArgs(params, method)
maybe `build_args` would be better for consistency?

2023-12-20 11:36 UTC, willothy approved these changes

2023-12-20 23:26 UTC, tris203 commented
also adds frame work for testing needed for #17

2023-12-20 23:27 UTC, willothy commented on lua/hawtkeys/init.lua
> +M._defaultSet = {
Should this be a local? Seems like it shouldn't need to be exposed externally other than through config

2023-12-20 23:30 UTC, willothy commented on lua/hawtkeys/init.lua
> +vim.api.nvim_create_user_command(
I think these should go in `setup`

2023-12-20 23:34 UTC, willothy approved these changes
lgtm!

2023-12-20 23:35 UTC, merged