ci:Cross platform tests
tris203/hawtkeys.nvim pull request #68
Opened 2024-01-02 19:16 UTC by tris203

2024-01-07 00:32 UTC, willothy requested changes
Just a few small things then lgtm

2024-01-07 00:32 UTC, willothy commented on lua/hawtkeys/ts.lua
> +        local paths = vim.fn.stdpath("config")
This should always be a single path as far as I know

2024-01-07 00:32 UTC, willothy commented on tests/hawtkeys/ui_spec.lua
> +                end)())
```suggestion
                ui.SearchBuf,
                ui.SearchWin,
                ui.ResultBuf,
                ui.ResultWin,
                ui.Namespace,
                ui.prompt_extmark
```

2024-01-07 00:32 UTC, willothy commented on tests/hawtkeys/ui_spec.lua
>              SearchBuf, SearchWin, ResultBuf, ResultWin, Namespace, prompt_extmark =
```suggestion
            local ui = require("hawtkeys.ui")
            SearchBuf, SearchWin, ResultBuf, ResultWin, Namespace, prompt_extmark =
```

2024-01-07 00:32 UTC, willothy commented on tests/hawtkeys/ui_spec.lua
>                  }
```suggestion
            local ui = require("hawtkeys.ui")
            ResultBuf, ResultWin, Namespace = ui.ResultBuf, ui.ResultWin, ui.Namespace
```

2024-01-07 00:32 UTC, willothy commented on tests/hawtkeys/ui_spec.lua
> +            end)())
```suggestion
```

2024-01-07 00:32 UTC, willothy commented on tests/hawtkeys/ui_spec.lua
>                  }
```suggestion
            vim.cmd([[lua require("hawtkeys.ui").show_dupes()]])
            local ui = require("hawtkeys.ui")
            ResultBuf, ResultWin, Namespace = ui.ResultBuf, ui.ResultWin, ui.Namespace
```

2024-01-07 00:32 UTC, willothy commented on tests/hawtkeys/ui_spec.lua
> +            end)())
```suggestion
```

2024-03-29 23:24 UTC, tris203 commented
@willothy do you think this is ready to merge too?

2024-03-30 21:19 UTC, willothy commented
> @willothy do you think this is ready to merge too?

CI passing so yessir, lgtm!

2024-03-30 21:20 UTC, willothy approved these changes

2024-03-30 21:49 UTC, merged